package com.bb.enums;

public enum LendingResultType {

    SUCCESSFUL_LEND,
    UNSUCCESSFUL_UNAVAILABLE_ITEM_LEND,
    UNSUCCESSFUL_BUSY_LOCK_LEND,

    SUCCESSFUL_RETURN,
    UNSUCCESSFUL_INVALID_ITEM_RETURN,
    UNSUCCESSFUL_BUSY_LOCK_RETURN
}
